name: UI Test

on:
  workflow_dispatch:

jobs:
  ui-test:
    name: UI Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone X','platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build and test
        run: |
          xcodebuild test -project RickAndMorty.xcodeproj -scheme RickAndMorty -destination 'platform=iOS Simulator,name=iPhone 13' -only-testing:RickAndMortyUITests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES
