name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        run: |
          xcodebuild  -project RickAndMorty.xcodeproj  -scheme RickAndMorty  -destination 'platform=iOS Simulator,name=iPhone 13' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

  SwiftLint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@main
      - name: Lint code using SwiftLint
        continue-on-error: true 
        run: swiftlint lint --reporter github-actions-logging 
      
  test:
    name: Test
    runs-on: macOS-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Unit Test
        run: |
          xcodebuild test -project RickAndMorty.xcodeproj -scheme RickAndMorty -destination 'platform=iOS Simulator,name=iPhone 13' -only-testing:RickAndMortyTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES
 
