name: Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 12','platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build and test
        run: |
          xcodebuild  -project RickAndMorty.xcodeproj  -scheme RickAndMorty  -destination 'platform=iOS Simulator,name=iPhone 13' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
        env: 
         destination: ${{ matrix.destination }}
         
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone X','platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build and test
        run: |
          xcodebuild test -project RickAndMorty.xcodeproj -scheme RickAndMorty -destination 'platform=iOS Simulator,name=iPhone 13' -only-testing:RickAndMortyTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES
 
